# Generated by Django 3.2 on 2022-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220417_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='soils',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
