# Generated by Django 3.2.25 on 2024-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_leafdiseasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafdiseasehistory',
            name='image',
            field=models.TextField(),
        ),
    ]
